### ISSUE TITLE
New Certificate isn't generated after domain change.

### ISSUE THREAD

**Issue by chespinoza** [dkumor/acmewrapper#8] opened 2016-07-19 05:44 UTC
How can I remove an existing certificate for a server? 

I tested a server with one domain, and then I tried with another domain, but the old domain certificate is alive yet , are there a way to force a domain change? I did the change into the code but doesn't work.

ie: 
first run with:
Domains: []string{"example.com","www.example.com"} 
then
Domains: []string{"example2.com","www.example2.com"}

and the server remains showing the example.com domain certificate and doesn't generate a new certificate for the new domain.

**Comment by chespinoza** [comment] 2016-07-19 06:20
Sorry, I just fix the problem simply deleting the key and cert (reg and pem) files and running again my app.

**Comment by dkumor** [comment] 2016-07-19 12:19
This is a bug - acmewrapper only checks for existence of certificates on startup, but not the domain. I'll see if I can fix it some time today.

**Comment by dkumor** [comment] 2016-07-20 16:22
Can you confirm that the issue is now fixed?

**Closed** 2016-07-20 16:21 UTC

**Comment by chespinoza** [comment] 2016-07-20 21:13
Ok let me check again, thanks

**Comment by chespinoza** [comment] 2016-11-02 16:03
Confirmed! Thanks and sorry for the delay.

**Comment by dkumor** [comment] 2016-11-02 21:06
:)
